---
- name: combine postgresql_backup configuration
  set_fact:
    postgresql_backup: "{{ _postgresql_backup|combine(postgresql_backup, recursive=True) }}"

- include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- include_tasks: packages.yml

- name: generate backup script
  become: true
  template:
    src: templates/postgresql-backup-script.sh.j2
    dest: /opt/postgresql-backup-script.sh
    owner: "{{ postgresql_backup.user }}"
    backup: true
    mode: 0755

- name: add backup script as cronjob
  become: true
  cron:
    name: backup postgres database
    cron_file: 'wingcon_psql'
    minute: "{{ postgresql_backup.cron_minute | default( '*' ) }}"
    hour: "{{ postgresql_backup.cron_hour | default( '0' ) }}"
    job: /opt/postgresql-backup-script.sh >/dev/null 2>&1
    user: "{{ postgresql_backup.user }}"
  when: postgresql_backup.cron
